## Default Kibana configuration from Kibana base image.

server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
elasticsearch.username: "${ELASTIC_USER}"
elasticsearch.password: "${ELASTIC_PASSWORD}"
